List univeristy = [
  'Air University (AU), Islamabad',
  'Allama Iqbal Open University (AIOU), Islamabad',
  'Bahria University (BU), Islamabad',
  'COMSATS Institute of Information Technology, Islamabad (having campuses; Islamabad, Abbottabad, Wah, Lahore and Attock). ',
  'Federal Urdu University of Arts, Sciences and Technology (FUUAST), Islamabad',
  'Foundation University, Islamabad',
  'Institute of Space Technology (IST), Islamabad',
  'International Islamic University (IIU), Islamabad',
  'National University of Computer and Emerging Sciences (NUCES), Islamabad',
  'National University of Modern Languages (NUML), Islamabad ',
  'Pakistan Institute of Engineering & Applied Sciences (PIEAS), Islamabad',
  'Quaid-i-Azam University (QAU), Islamabad',
  'Riphah International University (RIU), Islamabad',
  'Bahauddin Zakariya University (BZU), Multan',
  'Beaconhouse National University (BNU), Lahore',
  'College of Buisness Administration& Economics (NCBA&E) Lahore',
  'Hajvery University (HU), Lahore',
  'Fatima Jinnah Women University (FJWU), Rawalpindi',
  'Forman Christian College (FCC), Lahore',
  'GIFT University, Gujranwala',
  'Government College University (GCU), Faisalabad',
  'Government College University (GCU), Lahore',
  'Imperial College of Business Studies, Lahore',
  'Institute of Management Sciences (IMS), Lahore',
  'Islamia University, Bahawalpur',
  'Kinnaird College for Women, Lahore',
  'Lahore College for Women University (LCWU), Lahore',
  'Lahore School of Economics (LSE), Lahore',
  'Lahore University of Management Sciences (LUMS), Lahore',
  'Minhaj University, Lahore',
  'National College of Arts (NCA), Lahore',
  'National Textile University (NTU), Faisalabad (Federal Chartered)',
  'National University of Sciences & Technology (NUST), Rawalpindi',
  'The Superior College, Lahore ',
  'The University of Management & Technology (UMT), Lahore   ',
  'University of Agriculture, Faisalabad',
  'University of Arid Agriculture, Murree Road, Rawalpindi',
  'University of Central Punjab (UCP), Lahore',
  'University of Education, Lahore',
  'University of Engineering & Technology (UET), Lahore',
  'University of Engineering & Technology (UET), Taxila ',
  'University of Faisalabad, Faisalabad',
  'University of Gujrat , Gujrat',
  'University of Health Sciences (UHS), Lahore',
  'University of Lahore, Lahore',
  'University of Sargodha, Sargodha',
  'University of South Asia (USA), Lahore',
  'University of Veterinary and Animal Sciences (UVAS), Lahore',
  'Virtual University of Pakistan (VU), Lahore',
  'Agha Khan University (AKU), Karachi',
  'Baqai Medical University, Karachi',
  'Dadabhoy Institute of Higher Education, Karachi',
  'Dow University of Health Sciences Karachi',
  'Greenwich University, Karachi',
  'Hamdard University, Karachi',
  'Indus Institute of Higher Education, Karachi',
  'Indus Valley School of Art and Architecture, Karachi',
  'Institute of Business & Technology BIZTEK, Karachi',
  'Institute of Business Administration (IBA), Karachi',
  'Institute of Business Management (IoBM), Karachi',
  'Iqra University, Karachi',
  'Isra University, Hyderabad',
  'Jinnah University for Women, Karachi',
  'Karachi Institute of Economics & Technology (KIET), Karachi',
  'KASB (Khadim Ali Shah Bukhari) Institute of Technology, Karachi',
  'Liaquat University of Medical and Health Sciences (LUMHS), Jamshoro Sindh',
  'Mehran University of Eng. & Technology, Jamshoro',
  'Mohammad Ali Jinnah University (MAJU), Karachi',
  'NED University of Engineering & Technology, Karachi',
  'Newports Institute of Communications and Economics, Karachi',
  'Pakistan Naval Academy, Karachi',
  'Preston Institute of Management Sciences and Technology (PIMSAT), Karachi',
  'Preston University, Karachi',
  'Quaid-e-Awam University of Engineering, Science & Technology, Nawabshah',
  'Shah Abdul Latif University, Khairpur',
  'Shaheed Zulfikar Ali Bhutto Institute of Science & Technology (SZABIST), Karachi',
  'Sindh Agriculture University, Tandojam',
  'Sir Syed University of Engg. & Technology (SSUET), Karachi',
  'Sukkur Institute of Business Administration, Sukkur',
  'Textile Institute of Pakistan (TIP), Karachi',
  'University of East, Hyderabad ',
  'University of Karachi (UoK), Karachi',
  'University of Sindh, Jamshoro ',
  'Zia-ud-Din Medical University, Karachi',
  'Balochistan University of Engineering and Technology, Khuzdar',
  'Balochistan University of Information Technology and Management Sciences, Quetta',
  'Iqra University, Quetta',
  'Sardar Bahadur Khan Women University, Quetta',
  'University of Balochistan, Quetta',
  'Frontier Women University, Peshawar',
  'CECOS University of Information Technology and Emerging Sciences, Peshawar',
  'City University of Science & Information Technology, Peshawar',
  'Gandhara University, Peshawar',
  'Ghulam Ishaq Khan Institute of Engineering Sciences & Technology, Swabi',
  'Gomal University, D.I. Khan',
  'Hazara University, Dodhial, Mansehra',
  'Institute of Management Sciences (IMSciences), Peshawar',
  'Karakuram International University, Gilgit',
  'Kohat University of Science & Technology (KUST), Kohat',
  'Lasbelaa University of Agriculture, Water & Marine Science, Othal ',
  'Northern University, Nowshera Cantonment',
  'NWFP Agriculture University, Peshawar',
  'NWFP University of Engineering & Technology, Peshawar',
  'Pakistan Military Academy, Abbottabad',
  'Preston University, Kohat',
  'Qurtaba University of Science & Information Technology, D. I. Khan',
  'Sarhad University of Science & Information Technology, Peshawar (Approved Distance Education Centers of (SUIT), Peshawar)',
  'University of Malakand, Chakdara, Dir. Malakand',
  'University of Peshawar, Peshawar ',
  'University of Science & Technology, Bannu',
];
